-- ============================================
-- Main Warehouse - Complete Database Schema
-- ============================================

-- ============================================
-- AUTO-UPDATE TRIGGER FUNCTION
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PRODUCTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  archived_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_is_archived ON products(is_archived);
CREATE INDEX IF NOT EXISTS idx_products_updated_at ON products(updated_at);
CREATE INDEX IF NOT EXISTS idx_products_quantity ON products(quantity);

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_active_name
  ON products(name) WHERE is_archived = false;

DROP TRIGGER IF EXISTS set_products_updated_at ON products;
CREATE TRIGGER set_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- HISTORY TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  operation_type TEXT NOT NULL CHECK (operation_type IN ('IN', 'OUT')),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_history_product_id ON history(product_id);
CREATE INDEX IF NOT EXISTS idx_history_created_at ON history(created_at);
CREATE INDEX IF NOT EXISTS idx_history_operation_type ON history(operation_type);
CREATE INDEX IF NOT EXISTS idx_history_product_op ON history(product_id, operation_type);

-- ============================================
-- SETTINGS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_name TEXT NOT NULL DEFAULT 'Main Warehouse',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT settings_single_row CHECK (id = 1)
);

DROP TRIGGER IF EXISTS set_settings_updated_at ON settings;
CREATE TRIGGER set_settings_updated_at
  BEFORE UPDATE ON settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

INSERT INTO settings (id, warehouse_name)
VALUES (1, 'المستودع الرئيسي')
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- VIEW: PRODUCT DETAILS (with totals)
-- ============================================
CREATE OR REPLACE VIEW product_details_view AS
SELECT
  p.id,
  p.name,
  p.quantity,
  p.created_at AS arrival_date,
  p.updated_at AS last_update,
  p.is_archived,
  p.archived_at,
  COALESCE(in_stats.total_in, 0) AS total_in,
  COALESCE(out_stats.total_out, 0) AS total_out,
  GREATEST(p.quantity, 0) AS remaining_stock
FROM products p
LEFT JOIN (
  SELECT product_id, SUM(quantity) AS total_in
  FROM history WHERE operation_type = 'IN'
  GROUP BY product_id
) in_stats ON p.id = in_stats.product_id
LEFT JOIN (
  SELECT product_id, SUM(quantity) AS total_out
  FROM history WHERE operation_type = 'OUT'
  GROUP BY product_id
) out_stats ON p.id = out_stats.product_id;

-- ============================================
-- VIEW: WEEKLY OUT SUMMARY
-- ============================================
CREATE OR REPLACE VIEW weekly_out_summary AS
SELECT
  p.id AS product_id,
  p.name AS product_name,
  COALESCE(SUM(h.quantity), 0) AS total_out
FROM products p
LEFT JOIN history h ON p.id = h.product_id
  AND h.operation_type = 'OUT'
  AND h.created_at >= DATE_TRUNC('week', NOW())::date
  AND h.created_at < (DATE_TRUNC('week', NOW())::date + INTERVAL '7 days')
GROUP BY p.id, p.name
ORDER BY total_out DESC;

-- ============================================
-- VIEW: MONTHLY OUT SUMMARY
-- ============================================
CREATE OR REPLACE VIEW monthly_out_summary AS
SELECT
  p.id AS product_id,
  p.name AS product_name,
  COALESCE(SUM(h.quantity), 0) AS total_out
FROM products p
LEFT JOIN history h ON p.id = h.product_id
  AND h.operation_type = 'OUT'
  AND h.created_at >= DATE_TRUNC('month', NOW())::date
  AND h.created_at < (DATE_TRUNC('month', NOW())::date + INTERVAL '1 month')
GROUP BY p.id, p.name
ORDER BY total_out DESC;

-- ============================================
-- VIEW: TODAY SUMMARY
-- ============================================
CREATE OR REPLACE VIEW today_summary AS
SELECT
  COALESCE(SUM(CASE WHEN operation_type = 'IN' THEN quantity ELSE 0 END), 0) AS total_in,
  COALESCE(SUM(CASE WHEN operation_type = 'OUT' THEN quantity ELSE 0 END), 0) AS total_out
FROM history
WHERE created_at::date = CURRENT_DATE;

-- ============================================
-- FUNCTION: CHECK DUPLICATE PRODUCT
-- ============================================
CREATE OR REPLACE FUNCTION check_duplicate_product(p_name TEXT, p_exclude_id BIGINT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_count INTEGER;
BEGIN
  IF p_exclude_id IS NOT NULL THEN
    SELECT COUNT(*) INTO v_count
    FROM products
    WHERE LOWER(name) = LOWER(p_name)
      AND id != p_exclude_id
      AND is_archived = false;
  ELSE
    SELECT COUNT(*) INTO v_count
    FROM products
    WHERE LOWER(name) = LOWER(p_name)
      AND is_archived = false;
  END IF;
  RETURN v_count > 0;
END;
$$;

-- ============================================
-- FUNCTION: INCREASE STOCK (ATOMIC)
-- ============================================
CREATE OR REPLACE FUNCTION increase_stock(
  p_product_id BIGINT,
  p_quantity INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_product products;
BEGIN
  SELECT * INTO v_product FROM products WHERE id = p_product_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'PRODUCT_NOT_FOUND');
  END IF;

  UPDATE products
  SET quantity = quantity + p_quantity
  WHERE id = p_product_id
  RETURNING * INTO v_product;

  INSERT INTO history (product_id, operation_type, quantity)
  VALUES (p_product_id, 'IN', p_quantity);

  RETURN jsonb_build_object(
    'success', true,
    'product', row_to_json(v_product)
  );
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- ============================================
-- FUNCTION: DECREASE STOCK (ATOMIC)
-- ============================================
CREATE OR REPLACE FUNCTION decrease_stock(
  p_product_id BIGINT,
  p_quantity INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_product products;
  v_current_qty INTEGER;
BEGIN
  SELECT quantity INTO v_current_qty FROM products WHERE id = p_product_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'PRODUCT_NOT_FOUND');
  END IF;

  IF v_current_qty < p_quantity THEN
    RETURN jsonb_build_object('success', false, 'error', 'INSUFFICIENT_STOCK');
  END IF;

  UPDATE products
  SET quantity = quantity - p_quantity
  WHERE id = p_product_id
  RETURNING * INTO v_product;

  INSERT INTO history (product_id, operation_type, quantity)
  VALUES (p_product_id, 'OUT', p_quantity);

  RETURN jsonb_build_object(
    'success', true,
    'product', row_to_json(v_product)
  );
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- ============================================
-- FUNCTION: ADD PRODUCT WITH DUPLICATE CHECK
-- ============================================
CREATE OR REPLACE FUNCTION add_product(
  p_name TEXT,
  p_quantity INTEGER DEFAULT 0,
  p_arrival_date TIMESTAMPTZ DEFAULT NOW()
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_product products;
BEGIN
  IF check_duplicate_product(p_name) THEN
    RETURN jsonb_build_object('success', false, 'error', 'DUPLICATE_PRODUCT');
  END IF;

  INSERT INTO products (name, quantity, created_at)
  VALUES (p_name, p_quantity, p_arrival_date)
  RETURNING * INTO v_product;

  RETURN jsonb_build_object('success', true, 'product', row_to_json(v_product));
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- ============================================
-- FUNCTION: GET DASHBOARD STATS
-- ============================================
CREATE OR REPLACE FUNCTION get_dashboard_stats()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_total_products INTEGER;
  v_total_quantity BIGINT;
  v_added_today INTEGER;
  v_removed_today INTEGER;
  v_total_archived INTEGER;
  v_month_in INTEGER;
  v_month_out INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_total_products FROM products WHERE is_archived = false;
  SELECT COALESCE(SUM(quantity), 0) INTO v_total_quantity FROM products WHERE is_archived = false;

  SELECT COALESCE(SUM(CASE WHEN operation_type = 'IN' THEN quantity ELSE 0 END), 0),
         COALESCE(SUM(CASE WHEN operation_type = 'OUT' THEN quantity ELSE 0 END), 0)
  INTO v_added_today, v_removed_today
  FROM history WHERE created_at::date = CURRENT_DATE;

  SELECT COUNT(*) INTO v_total_archived FROM products WHERE is_archived = true;

  SELECT COALESCE(SUM(CASE WHEN operation_type = 'IN' THEN quantity ELSE 0 END), 0),
         COALESCE(SUM(CASE WHEN operation_type = 'OUT' THEN quantity ELSE 0 END), 0)
  INTO v_month_in, v_month_out
  FROM history
  WHERE created_at >= DATE_TRUNC('month', NOW())::date;

  RETURN jsonb_build_object(
    'total_products', v_total_products,
    'total_quantity', v_total_quantity,
    'added_today', v_added_today,
    'removed_today', v_removed_today,
    'total_archived', v_total_archived,
    'month_in', v_month_in,
    'month_out', v_month_out
  );
END;
$$;

-- ============================================
-- DISABLE ROW LEVEL SECURITY (no auth)
-- ============================================
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE history DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
